# Generated by Django 3.1.4 on 2020-12-17 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('exp_date', models.DateTimeField()),
                ('holder', models.CharField(max_length=70)),
                ('number', models.CharField(max_length=16)),
                ('brand', models.CharField(max_length=70)),
            ],
        ),
    ]
