# Generated by Django 3.1.4 on 2020-12-17 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='cvv',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='exp_date',
            field=models.CharField(max_length=10),
        ),
    ]
