# Generated by Django 3.1.4 on 2020-12-18 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201217_0142'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreditCard',
            new_name='CreditCardModel',
        ),
    ]
