# Generated by Django 3.1.4 on 2020-12-19 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201218_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcardmodel',
            name='brand',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
