# Generated by Django 3.1.4 on 2020-12-22 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201219_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcardmodel',
            name='cvv',
            field=models.IntegerField(blank=True),
        ),
    ]
